# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LauncherEFT.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import subprocess
import minecraft_launcher_lib
from PyQt5 import QtCore, QtGui, QtWidgets
from uuid import uuid1
# Эти импорты не обязательны, вместо generate_username()[0] и str(uuid1()) можно оставить просто ''
from random_username.generate import generate_username



minecraft_directory = minecraft_launcher_lib.utils.get_minecraft_directory().replace('minecraft','LauncherEFT');

class LaunchThread(QtCore.QThread):
    def run(self):
        #version = self.VersionSelect.currentText()
        version = 'rd-132211'
        minecraft_launcher_lib.install.install_minecraft_version(version=version,
                                                        minecraft_directory=minecraft_directory)
        username = generate_username()[0]
        options = {
            'username': username,
            'uuid': str(uuid1()),
            'token': ''
         }

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(942, 620)
        Dialog.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(55, 144, 40, 255), stop:1 rgba(155, 163, 9));")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(-10, 530, 951, 91))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255, 20%);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")


        self.Start = QtWidgets.QPushButton(self.groupBox)
        self.Start.setGeometry(QtCore.QRect(830, 20, 101, 23))
        self.Start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Start.setMouseTracking(False)
        self.Start.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Start.setObjectName("Start")
        self.Start.clicked.connect(self.launch_game)


        self.Username = QtWidgets.QLineEdit(self.groupBox)
        self.Username.setEnabled(True)
        self.Username.setGeometry(QtCore.QRect(40, 20, 181, 21))
        self.Username.setStyleSheet("background-color: rgb(246, 255, 220);")
        self.Username.setInputMask("")
        self.Username.setText("")
        self.Username.setMaxLength(30)
        self.Username.setFrame(False)
        self.Username.setCursorPosition(0)
        self.Username.setObjectName("Username")

        self.VersionSelect = QtWidgets.QComboBox(self.groupBox)
        self.VersionSelect.setGeometry(QtCore.QRect(40, 50, 181, 22))
        self.VersionSelect.setStyleSheet("background-color: rgb(246, 255, 220);")
        self.VersionSelect.setCurrentText("")
        self.VersionSelect.setObjectName("VersionSelect")

        #Получение списка версий маинкрафта
        for version in minecraft_launcher_lib.utils.get_version_list():
            self.VersionSelect.addItem(version['id'])

        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(230, 20, 581, 21))
        self.progressBar.setStyleSheet("color: rgb(215, 250, 255);")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setVisible(False)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 941, 621))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("assets/mainimage.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 30, 761, 481))
        self.groupBox_2.setStyleSheet("background-color:rgb(200, 194, 19, 45%)\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()

        self.retranslateUi(Dialog)
        self.launch_thread = LaunchThread()
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Start.setText(_translate("Dialog", "Запуск"))
        self.Username.setPlaceholderText(_translate("Dialog", " Username"))

    def launch_game(self):
        self.launch_thread.start()


if __name__ == "__main__":
    QtWidgets.QApplication.setAttribute(QtCore.Qt.ApplicationAttribute.AA_EnableHighDpiScaling, True)
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
