# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Setings(object):
    def setupUi(self, Setings):
        Setings.setObjectName("Setings")
        Setings.resize(521, 353)
        Setings.setStyleSheet("\n"
"background-color: rgb(255, 208, 114);")
        self.gridLayoutWidget = QtWidgets.QWidget(Setings)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 501, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 240, 202);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.MaxMemory_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.MaxMemory_2.setStyleSheet("background-color: rgb(255, 240, 202);")
        self.MaxMemory_2.setObjectName("MaxMemory_2")
        self.gridLayout.addWidget(self.MaxMemory_2, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setStyleSheet("background-color: rgb(255, 240, 202);")
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.MaxMemory = QtWidgets.QLabel(self.gridLayoutWidget)
        self.MaxMemory.setStyleSheet("background-color: rgb(255, 240, 202);")
        self.MaxMemory.setObjectName("MaxMemory")
        self.gridLayout.addWidget(self.MaxMemory, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.MaxMemory_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.MaxMemory_3.setStyleSheet("background-color: rgb(255, 240, 202);")
        self.MaxMemory_3.setObjectName("MaxMemory_3")
        self.gridLayout.addWidget(self.MaxMemory_3, 2, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_3.setStyleSheet("background-color: rgb(255, 240, 202);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout.addWidget(self.comboBox_3, 2, 1, 1, 1)

        self.retranslateUi(Setings)
        QtCore.QMetaObject.connectSlotsByName(Setings)

    def retranslateUi(self, Setings):
        _translate = QtCore.QCoreApplication.translate
        Setings.setWindowTitle(_translate("Setings", "Form"))
        self.MaxMemory_2.setText(_translate("Setings", "Максимальный размер выделенной памяти"))
        self.MaxMemory.setText(_translate("Setings", "Максимальный размер выделенной памяти"))
        self.MaxMemory_3.setText(_translate("Setings", "Язык"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Setings = QtWidgets.QWidget()
    ui = Ui_Setings()
    ui.setupUi(Setings)
    Setings.show()
    sys.exit(app.exec_())
